stages:
    - install
    - build

npm:
    stage: install
    only:
        - develop
        - release
    cache:
        paths:
            - node_modules
    script:
        - echo ${NPM_PRIVATE_REPOSITORY_PATH}
        - npm config set @mv:registry=${NPM_PRIVATE_REPOSITORY_PATH}
        - npm install --legacy-peer-deps

build:
    stage: build
    only:
        - develop
        - release
    before_script:
        - echo 'build start'
    cache:
        paths:
            - dist
    script:
        - npm run build